development:
  adapter: postgresql
  database: open_source_champion_api_development
  pool: 5
  timeout: 500

test:
  adapter: postgresql
  database: open_source_champion_api_development
  pool: 5
  timeout: 500

production:
  adapter: postgresql
  database: ENV['DATABASE_URL']
  pool: 5
  timeout: 500
