
development:
  adapter: postgresql
  encoding: unicode
  database: open-source-chamption-api_development
  pool: 5
  username: jared
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: open-source-chamption-api_test
  pool: 5
  username: jared
  password:
  timeout: 5000
