# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea065efcea07932f59a3563ec791d6daadee80a8b1b441bcb1d62050175d461b978dd32820ca6c3d58f1d70b18a88b2aee8603dd9aa808e45aee3c9eff43395

test:
  secret_key_base: 710044394803ec8efa1a243c9626993817249a092927d1228927235a2be2af5a8fd67fe979c7ffc3f5f004eee44987946cc352b448699f8114cdf1979a9cfea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
