# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389c3e1373ae4e176cbbb157fdf0f44af0b2e464e9d73b6c7550c5423c17fc35da509238b976eaaae5a1ad50f59b0eec0396f81df99a8909f4e9d80f7a64ae1c

test:
  secret_key_base: c48dbb21caba1c50ff2bedbbd9b4052c22721142e40e70e94ac10a13eaecd578fcfcebc341e83d026efca675afec88a45123f082e257f70b1f35146724556a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
